### PR TITLE
Hw 7 2

### PR DESCRIPTION
**Pull request by HrynkevychVitaliy**
"[HW 7.2]: Added Rubocop"

### CODE REVIEW

**Review by NickUkraine24 — COMMENTED** [review]
Please, do `bundle install`.

**Comment by HrynkevychVitaliy** [comment]
> Please, do `bundle install`.

Did while performing HW

**Comment by NickUkraine24** [comment]
> > Please, do `bundle install`.
> 
> Did while performing HW

At this moment, I see that you haven't committed `Gemfile.lock` and I think that you didn't run the command above.
Please, resolve this issue.

**Comment by HrynkevychVitaliy** [comment]
> > > Please, do `bundle install`.
> > 
> > 
> > Did while performing HW
> 
> At this moment, I see that you haven't committed `Gemfile.lock` and I think that you didn't run the command above.
> Please, resolve this issue.

What about now?

**Pull request merged**
